/**
 * This class is generated by jOOQ
 */
package by.silverscreen.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.NotificationsRecord> UNIQ_LOGIN = UniqueKeys0.UNIQ_LOGIN;
	public static final org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.PhoneRecord> PHONE_PK = UniqueKeys0.PHONE_PK;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.NotificationsRecord> UNIQ_LOGIN = createUniqueKey(by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS, by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.ID);
		public static final org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.PhoneRecord> PHONE_PK = createUniqueKey(by.silverscreen.jooq.tables.Phone.PHONE, by.silverscreen.jooq.tables.Phone.PHONE.DATA_ID);
	}
}
