/**
 * This class is generated by jOOQ
 */
package by.silverscreen.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.notifications
	 */
	public static final by.silverscreen.jooq.tables.Notifications NOTIFICATIONS = by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS;

	/**
	 * The table public.phone
	 */
	public static final by.silverscreen.jooq.tables.Phone PHONE = by.silverscreen.jooq.tables.Phone.PHONE;

	/**
	 * The table public.user_roles
	 */
	public static final by.silverscreen.jooq.tables.UserRoles USER_ROLES = by.silverscreen.jooq.tables.UserRoles.USER_ROLES;

	/**
	 * The table public.users
	 */
	public static final by.silverscreen.jooq.tables.Users USERS = by.silverscreen.jooq.tables.Users.USERS;
}
