/**
 * This class is generated by jOOQ
 */
package by.silverscreen.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationsRecord extends org.jooq.impl.UpdatableRecordImpl<by.silverscreen.jooq.tables.records.NotificationsRecord> implements org.jooq.Record10<java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Long, java.lang.String> {

	private static final long serialVersionUID = 606911106;

	/**
	 * Setter for <code>public.notifications.id</code>.
	 */
	public void setId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.notifications.id</code>.
	 */
	public java.lang.String getId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.notifications.films</code>.
	 */
	public void setFilms(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.notifications.films</code>.
	 */
	public java.lang.String getFilms() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.notifications.tikets</code>.
	 */
	public void setTikets(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.notifications.tikets</code>.
	 */
	public java.lang.String getTikets() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.notifications.startnotif</code>.
	 */
	public void setStartnotif(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.notifications.startnotif</code>.
	 */
	public java.lang.Long getStartnotif() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>public.notifications.endnotif</code>.
	 */
	public void setEndnotif(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.notifications.endnotif</code>.
	 */
	public java.lang.Long getEndnotif() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>public.notifications.wantrecieve</code>.
	 */
	public void setWantrecieve(java.lang.Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.notifications.wantrecieve</code>.
	 */
	public java.lang.Boolean getWantrecieve() {
		return (java.lang.Boolean) getValue(5);
	}

	/**
	 * Setter for <code>public.notifications.morningsend</code>.
	 */
	public void setMorningsend(java.lang.Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.notifications.morningsend</code>.
	 */
	public java.lang.Boolean getMorningsend() {
		return (java.lang.Boolean) getValue(6);
	}

	/**
	 * Setter for <code>public.notifications.filmreminder</code>.
	 */
	public void setFilmreminder(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.notifications.filmreminder</code>.
	 */
	public java.lang.Boolean getFilmreminder() {
		return (java.lang.Boolean) getValue(7);
	}

	/**
	 * Setter for <code>public.notifications.time</code>.
	 */
	public void setTime(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.notifications.time</code>.
	 */
	public java.lang.Long getTime() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>public.notifications.login</code>.
	 */
	public void setLogin(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.notifications.login</code>.
	 */
	public java.lang.String getLogin() {
		return (java.lang.String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Long, java.lang.String> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Long, java.lang.String> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.FILMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.TIKETS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.STARTNOTIF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.ENDNOTIF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field6() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.WANTRECIEVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field7() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.MORNINGSEND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.FILMREMINDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS.LOGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFilms();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTikets();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getStartnotif();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getEndnotif();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value6() {
		return getWantrecieve();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value7() {
		return getMorningsend();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getFilmreminder();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getLogin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value1(java.lang.String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value2(java.lang.String value) {
		setFilms(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value3(java.lang.String value) {
		setTikets(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value4(java.lang.Long value) {
		setStartnotif(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value5(java.lang.Long value) {
		setEndnotif(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value6(java.lang.Boolean value) {
		setWantrecieve(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value7(java.lang.Boolean value) {
		setMorningsend(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value8(java.lang.Boolean value) {
		setFilmreminder(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value9(java.lang.Long value) {
		setTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord value10(java.lang.String value) {
		setLogin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NotificationsRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.Long value4, java.lang.Long value5, java.lang.Boolean value6, java.lang.Boolean value7, java.lang.Boolean value8, java.lang.Long value9, java.lang.String value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NotificationsRecord
	 */
	public NotificationsRecord() {
		super(by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS);
	}

	/**
	 * Create a detached, initialised NotificationsRecord
	 */
	public NotificationsRecord(java.lang.String id, java.lang.String films, java.lang.String tikets, java.lang.Long startnotif, java.lang.Long endnotif, java.lang.Boolean wantrecieve, java.lang.Boolean morningsend, java.lang.Boolean filmreminder, java.lang.Long time, java.lang.String login) {
		super(by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS);

		setValue(0, id);
		setValue(1, films);
		setValue(2, tikets);
		setValue(3, startnotif);
		setValue(4, endnotif);
		setValue(5, wantrecieve);
		setValue(6, morningsend);
		setValue(7, filmreminder);
		setValue(8, time);
		setValue(9, login);
	}
}
