/**
 * This class is generated by jOOQ
 */
package by.silverscreen.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRolesRecord extends org.jooq.impl.UpdatableRecordImpl<by.silverscreen.jooq.tables.records.UserRolesRecord> implements org.jooq.Record3<java.lang.Short, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -148066046;

	/**
	 * Setter for <code>public.user_roles.user_role_id</code>.
	 */
	public void setUserRoleId(java.lang.Short value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.user_roles.user_role_id</code>.
	 */
	public java.lang.Short getUserRoleId() {
		return (java.lang.Short) getValue(0);
	}

	/**
	 * Setter for <code>public.user_roles.username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.user_roles.username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.user_roles.role</code>.
	 */
	public void setRole(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.user_roles.role</code>.
	 */
	public java.lang.String getRole() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Short> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Short, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Short, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field1() {
		return by.silverscreen.jooq.tables.UserRoles.USER_ROLES.USER_ROLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return by.silverscreen.jooq.tables.UserRoles.USER_ROLES.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return by.silverscreen.jooq.tables.UserRoles.USER_ROLES.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value1() {
		return getUserRoleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord value1(java.lang.Short value) {
		setUserRoleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord value2(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord value3(java.lang.String value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRolesRecord values(java.lang.Short value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRolesRecord
	 */
	public UserRolesRecord() {
		super(by.silverscreen.jooq.tables.UserRoles.USER_ROLES);
	}

	/**
	 * Create a detached, initialised UserRolesRecord
	 */
	public UserRolesRecord(java.lang.Short userRoleId, java.lang.String username, java.lang.String role) {
		super(by.silverscreen.jooq.tables.UserRoles.USER_ROLES);

		setValue(0, userRoleId);
		setValue(1, username);
		setValue(2, role);
	}
}
