/**
 * This class is generated by jOOQ
 */
package by.silverscreen.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notifications extends org.jooq.impl.TableImpl<by.silverscreen.jooq.tables.records.NotificationsRecord> {

	private static final long serialVersionUID = -861662833;

	/**
	 * The singleton instance of <code>public.notifications</code>
	 */
	public static final by.silverscreen.jooq.tables.Notifications NOTIFICATIONS = new by.silverscreen.jooq.tables.Notifications();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<by.silverscreen.jooq.tables.records.NotificationsRecord> getRecordType() {
		return by.silverscreen.jooq.tables.records.NotificationsRecord.class;
	}

	/**
	 * The column <code>public.notifications.id</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * The column <code>public.notifications.films</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.String> FILMS = createField("films", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

	/**
	 * The column <code>public.notifications.tikets</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.String> TIKETS = createField("tikets", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

	/**
	 * The column <code>public.notifications.startnotif</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.Long> STARTNOTIF = createField("startnotif", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.notifications.endnotif</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.Long> ENDNOTIF = createField("endnotif", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.notifications.wantrecieve</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.Boolean> WANTRECIEVE = createField("wantrecieve", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.notifications.morningsend</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.Boolean> MORNINGSEND = createField("morningsend", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.notifications.filmreminder</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.Boolean> FILMREMINDER = createField("filmreminder", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.notifications.time</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.Long> TIME = createField("time", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.notifications.login</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.NotificationsRecord, java.lang.String> LOGIN = createField("login", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.notifications</code> table reference
	 */
	public Notifications() {
		this("notifications", null);
	}

	/**
	 * Create an aliased <code>public.notifications</code> table reference
	 */
	public Notifications(java.lang.String alias) {
		this(alias, by.silverscreen.jooq.tables.Notifications.NOTIFICATIONS);
	}

	private Notifications(java.lang.String alias, org.jooq.Table<by.silverscreen.jooq.tables.records.NotificationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Notifications(java.lang.String alias, org.jooq.Table<by.silverscreen.jooq.tables.records.NotificationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, by.silverscreen.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.NotificationsRecord> getPrimaryKey() {
		return by.silverscreen.jooq.Keys.UNIQ_LOGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.NotificationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.NotificationsRecord>>asList(by.silverscreen.jooq.Keys.UNIQ_LOGIN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public by.silverscreen.jooq.tables.Notifications as(java.lang.String alias) {
		return new by.silverscreen.jooq.tables.Notifications(alias, this);
	}

	/**
	 * Rename this table
	 */
	public by.silverscreen.jooq.tables.Notifications rename(java.lang.String name) {
		return new by.silverscreen.jooq.tables.Notifications(name, null);
	}
}
