/**
 * This class is generated by jOOQ
 */
package by.silverscreen.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Phone extends org.jooq.impl.TableImpl<by.silverscreen.jooq.tables.records.PhoneRecord> {

	private static final long serialVersionUID = 644270597;

	/**
	 * The singleton instance of <code>public.phone</code>
	 */
	public static final by.silverscreen.jooq.tables.Phone PHONE = new by.silverscreen.jooq.tables.Phone();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<by.silverscreen.jooq.tables.records.PhoneRecord> getRecordType() {
		return by.silverscreen.jooq.tables.records.PhoneRecord.class;
	}

	/**
	 * The column <code>public.phone.data_id</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.PhoneRecord, java.util.UUID> DATA_ID = createField("data_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.phone.token</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.PhoneRecord, java.lang.String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

	/**
	 * The column <code>public.phone.login</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.PhoneRecord, java.lang.String> LOGIN = createField("login", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.phone.password</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.PhoneRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.phone.date</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.PhoneRecord, java.lang.Long> DATE = createField("date", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.phone.birth</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.PhoneRecord, java.lang.Long> BIRTH = createField("birth", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.phone.isman</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.PhoneRecord, java.lang.Long> ISMAN = createField("isman", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.phone.name</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.PhoneRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.phone.system</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.PhoneRecord, java.lang.String> SYSTEM = createField("system", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.phone</code> table reference
	 */
	public Phone() {
		this("phone", null);
	}

	/**
	 * Create an aliased <code>public.phone</code> table reference
	 */
	public Phone(java.lang.String alias) {
		this(alias, by.silverscreen.jooq.tables.Phone.PHONE);
	}

	private Phone(java.lang.String alias, org.jooq.Table<by.silverscreen.jooq.tables.records.PhoneRecord> aliased) {
		this(alias, aliased, null);
	}

	private Phone(java.lang.String alias, org.jooq.Table<by.silverscreen.jooq.tables.records.PhoneRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, by.silverscreen.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.PhoneRecord> getPrimaryKey() {
		return by.silverscreen.jooq.Keys.PHONE_PK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.PhoneRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.PhoneRecord>>asList(by.silverscreen.jooq.Keys.PHONE_PK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public by.silverscreen.jooq.tables.Phone as(java.lang.String alias) {
		return new by.silverscreen.jooq.tables.Phone(alias, this);
	}

	/**
	 * Rename this table
	 */
	public by.silverscreen.jooq.tables.Phone rename(java.lang.String name) {
		return new by.silverscreen.jooq.tables.Phone(name, null);
	}
}
