/**
 * This class is generated by jOOQ
 */
package by.silverscreen.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles extends org.jooq.impl.TableImpl<by.silverscreen.jooq.tables.records.UserRolesRecord> {

	private static final long serialVersionUID = -1719233163;

	/**
	 * The singleton instance of <code>public.user_roles</code>
	 */
	public static final by.silverscreen.jooq.tables.UserRoles USER_ROLES = new by.silverscreen.jooq.tables.UserRoles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<by.silverscreen.jooq.tables.records.UserRolesRecord> getRecordType() {
		return by.silverscreen.jooq.tables.records.UserRolesRecord.class;
	}

	/**
	 * The column <code>public.user_roles.user_role_id</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.UserRolesRecord, java.lang.Short> USER_ROLE_ID = createField("user_role_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.user_roles.username</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.UserRolesRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>public.user_roles.role</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.UserRolesRecord, java.lang.String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * Create a <code>public.user_roles</code> table reference
	 */
	public UserRoles() {
		this("user_roles", null);
	}

	/**
	 * Create an aliased <code>public.user_roles</code> table reference
	 */
	public UserRoles(java.lang.String alias) {
		this(alias, by.silverscreen.jooq.tables.UserRoles.USER_ROLES);
	}

	private UserRoles(java.lang.String alias, org.jooq.Table<by.silverscreen.jooq.tables.records.UserRolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserRoles(java.lang.String alias, org.jooq.Table<by.silverscreen.jooq.tables.records.UserRolesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, by.silverscreen.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<by.silverscreen.jooq.tables.records.UserRolesRecord, java.lang.Short> getIdentity() {
		return by.silverscreen.jooq.Keys.IDENTITY_USER_ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.UserRolesRecord> getPrimaryKey() {
		return by.silverscreen.jooq.Keys.USER_ROLES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.UserRolesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.UserRolesRecord>>asList(by.silverscreen.jooq.Keys.USER_ROLES_PKEY, by.silverscreen.jooq.Keys.USER_ROLES_ROLE_USERNAME_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public by.silverscreen.jooq.tables.UserRoles as(java.lang.String alias) {
		return new by.silverscreen.jooq.tables.UserRoles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public by.silverscreen.jooq.tables.UserRoles rename(java.lang.String name) {
		return new by.silverscreen.jooq.tables.UserRoles(name, null);
	}
}
