/**
 * This class is generated by jOOQ
 */
package by.silverscreen.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<by.silverscreen.jooq.tables.records.UsersRecord> {

	private static final long serialVersionUID = 1232318421;

	/**
	 * The singleton instance of <code>public.users</code>
	 */
	public static final by.silverscreen.jooq.tables.Users USERS = new by.silverscreen.jooq.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<by.silverscreen.jooq.tables.records.UsersRecord> getRecordType() {
		return by.silverscreen.jooq.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>public.users.username</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.UsersRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>public.users.password</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.UsersRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>public.users.enabled</code>.
	 */
	public final org.jooq.TableField<by.silverscreen.jooq.tables.records.UsersRecord, java.lang.Integer> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.users</code> table reference
	 */
	public Users() {
		this("users", null);
	}

	/**
	 * Create an aliased <code>public.users</code> table reference
	 */
	public Users(java.lang.String alias) {
		this(alias, by.silverscreen.jooq.tables.Users.USERS);
	}

	private Users(java.lang.String alias, org.jooq.Table<by.silverscreen.jooq.tables.records.UsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Users(java.lang.String alias, org.jooq.Table<by.silverscreen.jooq.tables.records.UsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, by.silverscreen.jooq.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.UsersRecord> getPrimaryKey() {
		return by.silverscreen.jooq.Keys.USERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<by.silverscreen.jooq.tables.records.UsersRecord>>asList(by.silverscreen.jooq.Keys.USERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public by.silverscreen.jooq.tables.Users as(java.lang.String alias) {
		return new by.silverscreen.jooq.tables.Users(alias, this);
	}

	/**
	 * Rename this table
	 */
	public by.silverscreen.jooq.tables.Users rename(java.lang.String name) {
		return new by.silverscreen.jooq.tables.Users(name, null);
	}
}
